version: "3.9"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge

  alurabooks:
    image: diodocker/dio-books:1.0
    container_name: diobooks
    networks:
      - compose-bridge
    ports:
      - 3001:3001

networks:
  compose-bridge:
    driver: bridge
